#Messages
1: Simple Virtual WorkBench Table disabled
2: Simple Virtual WorkBench enabled!
3: You don`t have permission to use the PORTABLE WORKBENCH
4: Opening crafting table...
5: You don't have enough money to use the PORTABLE WORKBENCH
6: Price
#Economy
#Enable or Disable the economy
Economy: false 
#Price to use the PORTABLE CRAFTING TABLE
Price: 5