name: SimpleVirtualWorkBench
main: io.github.galaipa.craft.Main
version: 1.0
author: Galaipa
description: Simple portable workbench plugin
softdepend: [Vault]

commands:
  craftingtable:
    description: Name command for items
    usage: /<command>
    aliases: [craft, workbench, wb]
    
permissions:
  spc.craft:
    description: Perm to use the portable crafting table
    default: op
  spc.free:
    description: Perm to use the portable crafting table for free
    deafault: false
