name: SimpleVirtualWorkBench
main: io.github.galaipa.craft.Main
version: 2.0
author: Galaipa
description: Simple portable workbench plugin
softdepend: [Vault]

commands:
  craftingtable:
    description: Name command for items
    usage: /<command>
    aliases: [craft, workbench, wb]
  svw:
    description: Update plugin
    usage: /<command>    
    
permissions:
  spc.craft:
    description: Perm to use the portable crafting table
    default: op
  spc.free:
    description: Perm to use the portable crafting table for free
    default: false
  spc.update:
    description: Perm to use updater command
    default: op
